### ISSUE TITLE
Keras 3, but this is not yet supported

### ISSUE THREAD

**Issue by csmsm** [AlexChristensen/transforEmotion#16]
HI, I am running zero-shot with DistilRoBERTa and using "transformer_scores." But got the error message as follows: 

"_impl(callable, call_args$unnamed, call_args$named) : 
  RuntimeError: Failed to import transformers.models.roberta.modeling_tf_roberta because of the following error (look up to see its traceback):
Your currently installed version of Keras is Keras 3, but this is not yet supported in Transformers. Please install the backwards-compatible tf-keras package with `pip install tf-keras`.
Run `reticulate::py_last_error()` for details." 

Please advise and many thanks.

**Comment by atomashevic** [comment]
Hi, thanks for opening this issue! This is a common new bug which is a result of mismatch between Keras and transformers. I will fix this is a few days (probably tomorrow) with new version of package first on github and then on CRAN.

I will post the instructions on how to avoid getting this error by installing new version.

**Comment by csmsm** [comment]
Super and many thanks.

**Comment by atomashevic** [comment]
The new version is on GitHub, not yet on CRAN. To avoid any issues with the librariess I would suggest the following steps:

```R
# remove minconda
reticulate::miniconda_uninstall()

# remove transforEmotion
remove.packages("transforEmotion")

# install from github
devtools::install_github("atomashevic/transforEmotion")

# load tE and setup miniconda
library(transforEmotion)

setup_miniconda()
```

After this, you should be good to go. Let me know if this solves your issue, so I can close it.

**Comment by csmsm** [comment]
it worked and many thanks. It looked to me that you "forced" an earlier
version of Keras. Would Keras 3 be used in the future? This is no rush but
I am just curious.

**Comment by atomashevic** [comment]
We are aligning all library versions according to what `transformers` need to do their job, because it's our main dependency. We will monitor future updates and adjust all versions accordingly.
